name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Grant permissions
        run: sudo chmod +x ./gradlew

      - name: Setup and build
        uses: gradle/gradle-build-action@v2
        with:
          tasks: 'assembleRelease'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/libre/release/app-libre-release-unsigned.apk
